name: CI/CD for File Extraction and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unrar

      - name: Download .rar File
        run: |
          wget --progress=bar:force:noscroll -O game.rar https://paster.vip/6wW72Ubm-DaysR.ER-GameDrive.Org.rar 2>&1 | tee download.log

      - name: Extract File
        id: extract
        run: |
          mkdir -p extracted
          unrar e game.rar "archive_root/BendGame/Content/Paks/Lang/en.pak" extracted/
          if [ -f "extracted/en.pak" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Check File and List Archive Contents
        run: |
          if [ -f "extracted/en.pak" ]; then
            echo "File exists, preparing for release"
          else
            echo "File not found, listing contents of the archive:"
            unrar l game.rar
          fi
        continue-on-error: true

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Create Release
        if: ${{ steps.extract.outputs.file_exists == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./extracted/en.pak
          tag_name: ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}